### ISSUE TITLE
"Select all" checkbox only toggles, should set all to same state

### ISSUE THREAD

**Issue by EthanJStark** [kofile/react-order-receipt#25]
Steps to reproduce:
- Check a box
- Check the "Select all" box

**Expected:**
All boxes become selected, including "select all". Another click leaves all boxes de-selected

**Actual:**
All boxes are toggled:
![screen shot 2018-12-12 at 2 21 43 pm](https://user-images.githubusercontent.com/19176630/49902616-49c3b400-fe19-11e8-8701-60792a439e8a.png)

**Comment by jgbenito7** [comment]
Think this bug is fixed?

**Comment by EthanJStark** [comment]
Yep, fixed
